---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```
# covidmodeldata

<!-- badges: start -->
<!-- badges: end -->

The goal of covidmodeldata is to download and format data

## Installation

``` r
remotes::install_github("nset-ornl/covidmodeldata")
```

## Download and Format New York Times Data

This is a basic example which shows you how to solve a common problem:
```{r example-run, echo=FALSE, message=FALSE, warning=FALSE}
library(covidmodeldata)
library(tidyverse)

df <- get_nyt() %>%
  format_nyt(
    skip_assignment = c("44") # don't assign Rhode Island cases
    )
```

```{r example, eval=FALSE}
library(covidmodeldata)
library(tidyverse)

df <- get_nyt() %>%
  format_nyt(
    skip_assignment = c("44") # don't assign Rhode Island cases
    )

glimpse(df)
```

```{r example-table, echo=FALSE}
glimpse(df)
```

## ACS data and Geometries
```{r}
glimpse(acs_data)
```


## Landscan USA Population Data
```{r}
glimpse(landscan_usa)
```



